* Config/Preamble :noexport:
** LaTeX Config
#+BEGIN_SRC emacs-lisp :exports none  :results none :eval always
  (add-to-list 'org-latex-classes
	       '("altacv"
		 "\\documentclass[10pt,a4paper,ragged2e,withhyper]{altacv}

  % Change the page layout if you need to
  \\geometry{left=1.25cm,right=1.25cm,top=1.5cm,bottom=1.5cm,columnsep=1.2cm}

  % Use roboto and lato for fonts
  \\renewcommand{\\familydefault}{\\sfdefault}

  % Change the colours if you want to
  \\definecolor{SlateGrey}{HTML}{2E2E2E}
  \\definecolor{LightGrey}{HTML}{666666}
  \\definecolor{DarkPastelRed}{HTML}{450808}
  \\definecolor{PastelRed}{HTML}{8F0D0D}
  \\definecolor{GoldenEarth}{HTML}{E7D192}
  \\colorlet{name}{black}
  \\colorlet{tagline}{PastelRed}
  \\colorlet{heading}{DarkPastelRed}
  \\colorlet{headingrule}{GoldenEarth}
  \\colorlet{subheading}{PastelRed}
  \\colorlet{accent}{PastelRed}
  \\colorlet{emphasis}{SlateGrey}
  \\colorlet{body}{LightGrey}

  % Change some fonts, if necessary
  \\renewcommand{\\namefont}{\\Huge\\rmfamily\\bfseries}
  \\renewcommand{\\personalinfofont}{\\footnotesize}
  \\renewcommand{\\cvsectionfont}{\\LARGE\\rmfamily\\bfseries}
  \\renewcommand{\\cvsubsectionfont}{\\large\\bfseries}

  % Change the bullets for itemize and rating marker
  % for \cvskill if you want to
  \\renewcommand{\\itemmarker}{{\\small\\textbullet}}
  \\renewcommand{\\ratingmarker}{\\faCircle}
  "
		 ("\\cvsection{%s}" . "\\cvsection*{%s}")
		 ("\\cvevent{%s}" . "\\cvevent*{%s}")))

  (setq org-latex-default-packages-alist
	'(("rm" "roboto"  t)
	  ("defaultsans" "lato" t)
	  ("" "paracol" t)))

  (setq org-latex-packages-alist 'nil)
#+END_SRC

#+LATEX_CLASS: altacv
#+LATEX_HEADER: \columnratio{0.6} % Set the left/right column width ratio to 6:4.
#+LATEX_HEADER: \usepackage[bottom]{footmisc}
*** Bibliograpny
#+LATEX_HEADER: \addbibresource{pankaj.bib}
# #+LATEX_HEADER: \usepackage[citestyle=numeric-comp, maxcitenames=1, maxbibnames=4, doi=false, isbn=false, eprint=true, backend=bibtex, hyperref=true, url=false, natbib=true]{biblatex}
#+LATEX_HEADER: \usepackage[backend=biber,style=alphabetic,sorting=ynt]{biblatex}

** Exporter Settings
#+AUTHOR: Pankaj Godbole
#+EXPORT_FILE_NAME: ./resume.pdf
#+OPTIONS: toc:nil title:nil H:1
** Macros
#+MACRO: small-skip    \smallskip
#+MACRO: med-skip      \medskip
#+MACRO: big-skip      \bigskip
#+MACRO: div           \divider
#+MACRO: par-div       \par\divider
#+MACRO: new-page      \newpage
#+MACRO: cvevent       \cvevent{$1}{$2}{$3}{$4}
#+MACRO: cvtag         \cvtag{$1}
#+MACRO: cvachievement \cvachievement{$1}{$2}{$3}{$4}
* CV Header :ignore:
** Photo & Tagline :ignore:
#+begin_export latex
\name{Pankaj Godbole}
\photoR{2.5cm}{portrait.jpeg}
\tagline{Clojure Developer}
#+end_export
** Personal Info :ignore:
#+begin_export latex
\medskip
\personalinfo{
  \homepage{pankajgodbole.github.io}
  \email{pankajsg@gmail.com}
  \phone{+91 96373 66884}
  \location{Pune, India}
  \github{pankajgodbole}
  \linkedin{pankajgodbole}}
\makecvheader
#+end_export

* CV Column 1 :ignore:
#+begin_export latex
\begin{paracol}{2}
#+end_export
** Summary
{{{big-skip}}}
#+begin_export latex
 \begin{quote}
 Senior engineer with many years of experience in developing applications and services on Linux, macOS, Windows, Android, JVM, and web-browser for Mobile, Cloud, Desktop and Embedded platforms. Skilled in requirements analysis, architecture high-level design, implementation, testing, deployment and maintenance. Domain experience includes AI, blockchain, fintech, mobile and e-commerce. Available now.
 \end{quote}
#+end_export
{{{big-skip}}}
** Experience
*** Freelance Developer :ignore:
{{{cvevent(Freelance Developer, Higher Order, 2014 -- Ongoing, Pune\, India)}}}
Building software of high quality at competitive rates for both established companies and early-stage startups.
- Provide “turn key” solutions comprising full product life cycle
- Produce reports and/or white papers on emerging technologies
- Ideate a product or service, build PoC and develop the MVP
- Employ best practices to reduce risk, accommodate change
- Ensure the maximum RoI for customers' investments
{{{med-skip}}}
{{{cvtag(Clojure)}}} {{{cvtag(ClojureScript)}}} {{{cvtag(React Native)}}} {{{cvtag(SPA)}}} {{{cvtag(Material Design)}}} {{{cvtag(Functional programming)}}} {{{cvtag(SQL)}}} {{{cvtag(REST)}}} {{{cvtag(AWS)}}} {{{cvtag(Docker)}}} {{{cvtag(git)}}} {{{cvtag(UI)}}} {{{cvtag(Test driven development)}}} {{{cvtag(Startups)}}}
*** Sr Engineer – Software :ignore:
{{{par-div}}}
{{{cvevent(Sr Engineer – Software, Logitech Designs India Pvt Ltd, 2010 -- 2013, Chennai\, India)}}}
Helped design and implement highly immersive and responsive Android apps and single page applications for Harmony universal remote controls and Revue Android TV in the Digital Home Group.
- Built an electronic program guide SPA using REST APIs from Rovi
- Worked on Android app for Revue Android TV remote control
- Served as Scrum Master
{{{med-skip}}}
{{{cvtag(Android)}}} {{{cvtag(Node.js)}}} {{{cvtag(JSON)}}} {{{cvtag(jQuery)}}} {{{cvtag(Bootstrap)}}} {{{cvtag(gerrit)}}}
# {{{cvtag(Jenkins)}}}
*** Android Consultant :ignore:
{{{div}}}
{{{cvevent(Android Consultant, Early-stage startups, 2009 -- 2010, Pune\, India)}}}
- Helped early-stage startups on their mobile journey
- Mentored developers new to Android app development
{{{med-skip}}}
{{{cvtag(Android)}}} {{{cvtag(SQLite)}}} {{{cvtag(XML)}}} {{{cvtag(Mobile)}}} {{{cvtag(Cloud)}}} {{{cvtag(Web)}}} {{{cvtag(Teamwork)}}}
*** Software Test Manager :ignore:
{{{div}}}
{{{cvevent(Software Test Manager, Ecrio Inc., 2008 -- 2009, Cupertino\, USA)}}}
- Managed the testing of SIP-based VoIP applications
- Built and led outsourced teams co-located in US and India
{{{med-skip}}}
{{{cvtag(Symbian)}}} {{{cvtag(Windows Mobile)}}} {{{cvtag(MS Project)}}} {{{cvtag(MS Excel)}}} {{{cvtag(Bugzilla)}}}
*** Software Engineer :ignore:
{{{div}}}
{{{cvevent(Software Engineer, Palm Inc., 2006 -- 2007, Sunnyvale\, USA)}}}
- Handled Wi-Fi–Bluetooth coexistence on Treo smartphones
- Worked closely with WLAN and BT hardware engineers
{{{med-skip}}}
{{{cvtag(PalmOS)}}} {{{cvtag(Windows Mobile)}}} {{{cvtag(Wi-Fi)}}} {{{cvtag(Bluetooth)}}} {{{cvtag(Wireshark)}}}
*** Senior Software Engineer :ignore:
{{{div}}}
{{{cvevent(Senior Software Engineer, Veriwave Inc., 2005 -- 2005, Sunnyvale\, USA)}}}
- Validated the VeriWave Command Language via extensive tests
- Tested the generated 802.11 frames at MAC and network layers
{{{med-skip}}}
{{{cvtag(802.11)}}} {{{cvtag(WLAN)}}} {{{cvtag(Python)}}} {{{cvtag(Tcl)}}} {{{cvtag(Wireshark)}}} {{{cvtag(QA)}}}
*** Systems Engineer :ignore:
{{{par-div}}}
{{{cvevent(Systems Engineer, Qorvus Systems, 2004 -- 2005, Vancouver\, USA)}}}
Hardware and software for wireless mesh networking access points (APs) for downtowns, 24/7 wireless video monitoring, remote sensing in industrial applications, etc.
- Created new revenue stream through a service called Qspot
- Designed a way to allow AP access by device's MAC address
- Automated signing, granting and revoking security certificates
{{{med-skip}}}
{{{cvtag(Ethernet)}}} {{{cvtag(PoE)}}} {{{cvtag(bash)}}} {{{cvtag(Linux)}}} {{{cvtag(CGI)}}} {{{cvtag(OpenSSL)}}}
*** Systems Analyst :ignore:
{{{par-div}}}
{{{cvevent(Systems Analyst, American Bureau of Shipping, 2000 -- 2001, Houston\, USA)}}}
Development of advanced 3-tier client-server Web services, for customers to submit engineering data for detailed modeling and analysis by ABS' engineers.
- Lead a team of three engineers through development lifecycle
- Assigned tasks, coordinated the development
- Provided training for new team members
{{{med-skip}}}
{{{cvtag(Java)}}} {{{cvtag(VRML)}}} {{{cvtag(Simulation technology)}}} {{{cvtag(XSLT)}}} {{{cvtag(Servlets)}}} {{{cvtag(LAMP)}}} {{{cvtag(Windows 2000)}}}
*** Software Engineer :ignore:
{{{new-page}}}
{{{cvevent(Software Engineer, Patni Computer Systems, 1997 -- 2000, Pune\, India)}}}
Work involved maintenance and enhancement of CAD/CAM software developed by Computer Vision Corporation and Parametric Technologies Corporation
- Ported C and C++ modules from Solaris to Windows NT
- Ran integration, system, regression and unit tests
- Performed QA based on ISO-9001 and CMM
- Educated team-members about CMM via a series of seminars
{{{med-skip}}}
{{{cvtag(CAD/CAM)}}} {{{cvtag(Capibility Maturity Model)}}} {{{cvtag(C)}}} {{{cvtag(C++)}}} {{{cvtag(Solaris)}}} {{{cvtag(Windows NT)}}}
{{{new-page}}}
** Newpage :ignore:noexport:
** Projects
*** React Native iOS and Android apps :ignore:
{{{cvevent(Developing native iOS and Android version of app, Urban Dictionary, Mar 2021 - Apr 2021, Remote)}}}
Worked on popular iOS and Android React Native apps
{{{cvtag(Clojurescript)}}} {{{cvtag(React Native)}}} {{{cvtag(re-frame)}}} {{{cvtag(shadow-cljs)}}} {{{cvtag(Expo.io)}}} {{{cvtag(Docker)}}}
*** UPI Code Migration :ignore:
{{{div}}}

{{{cvevent(Trajectory Optimisation in Learned Multimodal Dynamical Systems, University of Bristol, Sept 2019 - March 2021, Pune\, India)}}}

- Synergising Bayesian inference and Riemannian geometry to control multimodal dynamical systems.
   # Learning multimodal probabilistic transition dynamics.
- Finds trajectories that 1) remain in a desired dynamics mode, 2) avoid regions of the dynamics with high epistemic uncertainty.
- [[https://www.pankajgodbole.com/publication/trajectory-optimisation-in-learned-multimodal-dynamical-systems-via-latent-ode-collocation/paper.pdf][\faBook published @ ICRA 2021]]
- [[https://github.com/pankajgodbole/trajectory-optimisation-in-learned-multimodal-dynamical-systems][\faGithub pankajgodbole/trajectory-optimisation-in-learned-multimodal-dynamical-systems]]

{{{cvtag(JAX)}}}
{{{cvtag(Probabilistic geometries)}}}
{{{cvtag(Optimal control)}}}

*** SVGP :ignore:
{{{par-div}}}

{{{cvevent(Identifiable Mixtures of Sparse Variational Gaussian Process Experts, University of Bristol, Sept 2018 - Ongoing, Pune\, India)}}}

- Improving identifiability and scalability in the Mixtures of Gaussian Process Experts model with GP-based gating networks.
- Variational inference based on sparse GP approximations.
-  [[https://github.com/pankajgodbole/mogpe][\faGithub pankajgodbole/mogpe]]

{{{cvtag(GPflow)}}}
{{{cvtag(TensorFlow)}}}
{{{cvtag(Gaussian processes)}}}
{{{cvtag(Variational inference)}}}

*** GPJax :ignore:noexport:
{{{div}}}

{{{cvevent(Gaussian Processes in JAX (Code), Emacs, March 2021 - Ongoing, Pune\, India)}}}

- Minimal Gaussian process library in JAX with a simple (custom) approach to state management.
- \faGithub [[https://github.com/pankajgodbole/GPJax][pankajgodbole/GPJax]]

{{{cvtag(Gaussian processes)}}}
{{{cvtag(Variational inference)}}}
{{{cvtag(JAX)}}}
{{{cvtag(SVGP)}}}

** A day of my life :noexport:
# #+begin_export latex
# % \medskip

# % \cvsection{A Day of My Life}

# % % Adapted from @Jake's answer from http://tex.stackexchange.com/a/82729/226
# % % \wheelchart{outer radius}{inner radius}{
# % % comma-separated list of value/text width/color/detail}
# % \wheelchart{1.5cm}{0.5cm}{%
# %   6/8em/accent!30/{Sleep,\\beautiful sleep},
# %   3/8em/accent!40/Hopeful novelist by night,
# %   8/8em/accent!60/Daytime job,
# %   2/10em/accent/Sports and relaxation,
# %   5/6em/accent!20/Spending time with family
# % }

# % % use ONLY \newpage if you want to force a page break for
# % % ONLY the current column
# % \newpage
# #+end_export

** Newpage :ignore:noexport:
#+BEGIN_EXPORT latex
\newpage
#+END_EXPORT

** Volunteering
*** FARSCOPE Course Rep :ignore:
{{{cvevent(Cohort Representative, FARSCOPE CDT, Sept 2018 - Ongoing, Pune\, India)}}}
# - I represent myself and fellow CDT students in management meetings where I communicate ideas and information between students and management.
- Represent myself and my CDT peers in management meetings.
- Communicate information between students and management.

{{{cvtag(Communication)}}}
{{{cvtag(Interpersonal Skills)}}}

{{{par-div}}}

*** Code Club :ignore:
{{{cvevent(Club Leader, Code Club, Dec 2017 - April 2018, Junction 3 Library\, Bristol \, UK)}}}

# - I collaborated with [[https://codeclub.org/en/][Code Club]] and Bristol Libraries to set up and run a Code Club for young people aged 9-13.
# - Demonstrating my abi involved organising,  planning lessons and teaching
- Set up (and then ran) a [[https://codeclub.org/en/][Code Club]] for children aged 9-13.
- Led the organisation, planning and teaching of weekly lessons.
- Planned lessons to engage children by making coding fun.
- Extremely rewarding and reinforced my love for teaching.
# - @ Junction 3 Library in Easton, Bristol.

{{{cvtag(Leadership)}}}
{{{cvtag(Teaching)}}}
{{{cvtag(Communication)}}}
{{{cvtag(Active listening)}}}

*** Drivetrain :ignore:noexport:
{{{par-div}}}

{{{cvevent(Technical Lead (Drivetrain), Formula Student, Jan 2015 - Jan 2016, Pune\, India)}}}

Each year, as part of Formula Student, students design, build and race a single seat race car.
- Finished 2nd in the National Class 2 competition in 2013/2014, I was then selected as the Drivetrain lead.
- This role improved my communication skills as I was leading weekly presentations.
- I developed my leadership skills through setting realistic objectives, effectively allocating work to the appropriate team members and monitoring outcomes.

{{{cvtag(Teamwork)}}}
{{{cvtag(Leadership)}}}
{{{cvtag(Time Management)}}}

*** Snowboard Captain :ignore:noexport:
{{{par-div}}}

{{{cvevent(Snowboard Captain, University of Bristol Snowsports Club, Jan 2014 - Sept 2015, Pune\, India)}}}

- Organised multiple weekly training sessions, demonstrating my ability to plan and run events smoothly.
- Negotiated competitive prices for a growing member base within an inherently expensive sport.
- Responsible for aiding the smooth running of the club and helping to organise the annual university ski trip, with circa 1500 participants, working under pressure to manage people in high stress situations.
- Awarded the ‘Team of the Year’ award and full colours for my performances and contributions to the sport.

{{{cvtag(Teamwork)}}}
{{{cvtag(Leadership)}}}
{{{cvtag(Time Management)}}}

** Talks
*** Geometry Talk :ignore:
{{{cvevent(Synergising Bayesian Inference and Probabilistic Geometries for Robotic Control, Cognitive Systems - Technical University of Denmark (DTU), 18 March 2021, Zoom)}}}
# - Presented a method for controlling multimodal dynamical systems synergising Bayesian inference and probabilistic geometries.
- Presented a method that synergises Bayesian inference and probabilistic geometries to control multimodal dynamical systems.

{{{cvtag(Communication)}}}
{{{cvtag(Probabilistic geometries)}}}
{{{cvtag(Gaussian processes)}}}

** Publications
#+begin_export latex
\nocite{*}
% \printbibliography[heading=pubtype,title={\printinfo{\faBook}{Books}},type=book]
% \divider
% \printbibliography[heading=pubtype,title={\printinfo{\faFile*[regular]}{Journal Articles}},type=article]
% \divider
\printbibliography[heading=pubtype,title={\printinfo{\faUsers}{Conference Proceedings}},type=inproceedings]
#+end_export

* CV Column 2 :ignore:
# Switch to the right column - will automatically move to the next page.
#+begin_export latex
\switchcolumn
#+end_export

** Skills
{{{cvtag(Python)}}}
{{{cvtag(TensorFlow)}}}
{{{cvtag(GPflow)}}}
{{{cvtag(JAX)}}}
{{{cvtag(NumPy)}}}
{{{cvtag(SciPy)}}}
{{{cvtag(Matplotlib)}}}
{{{cvtag(GPy)}}}

{{{div}}}

{{{cvtag(Java)}}}
{{{cvtag(C++)}}}
{{{cvtag(MATLAB)}}}
{{{cvtag(ROS)}}}

{{{div}}}


{{{cvtag(Git/GitHub)}}}
{{{cvtag(LaTeX)}}}
{{{cvtag(Org-mode)}}}

** Education
{{{cvevent(PhD\ in Bayesian Machine Learning for Robotic Control, University of Bristol, Sept 2018 - Ongoing,)}}}

{{{div}}}

{{{cvevent(Gaussian Process and Uncertainty Quantification Summer School (GPSS), University of Sheffield, Sept 2019 - Sept 2019,)}}}

{{{div}}}

{{{cvevent(Machine Learning Summer School Moscow (MLSS), Skoltech, Aug 2019 - Sept 2019,)}}}

{{{div}}}

# {{{cvevent(M.Res.\ in Robotics \& Autonomous Systems, University of Bristol | First Class Honours, Sept 2017 -- Sept 2018,)}}}
# {{{cvevent(a \footnote{Not official - will be awarded if Ph.D. is not completed.} M.Res.\ in Robotics \& Autonomous Systems,University of Bristol,Sept 2017 -- Sept 2018,)}}}
#+BEGIN_EXPORT latex
\cvevent{\footnote{Not official - awarded if Ph.D. is not completed.} MRes in Robotics \& Autonomous Systems}{University of Bristol | First Class Honours}{Sept 2017 -- Sept 2018}{}
#+END_EXPORT
# - First Class Honours
- \faBook [[https://www.pankajscannell.com/project/uncertain-agentspeak/][Extending BDI Agents to Model and Reason with Uncertainty]]


{{{div}}}

{{{cvevent(MEng in Mechanical Engineering, University of Bristol | First Class Honours, Sept 2012 -- June 2016,)}}}
# - First Class Honours \\
- Graduated in top 10% of cohort

** Newpage :ignore:
#+BEGIN_EXPORT latex
\newpage
#+END_EXPORT

** My Life Philosophy :noexport:
#+begin_export latex
% \begin{quote}
% ``Something smart or heartfelt, preferably in one sentence.''
% \end{quote}
#+end_export

# ** Most Proud Of :ignore:
# #+begin_export latex
# \cvsection{Most Proud of}
# #+end_export

# #+begin_export latex
# \cvachievement{\faTrophy}{Code Club Leader}{Collaborated with Code Club and Bristol Libraries to set up and run a Code Club for 9-13 year olds.}
# #+end_export

# #+begin_export latex
# \divider

# \cvachievement{\faHeartbeat}{British University Snowboard Slalom Champion}{Won all national British university slalom competitions in 2017-2018.}
# #+end_export

** Achievements
{{{cvachievement(\faTrophy, Full Sporting Colours, Awarded full colours for outstanding achievements in snowboarding. Multiple gold medals in British University Snowboard Championships.)}}}

{{{div}}}

{{{cvachievement(\faCertificate, Starting To Teach, Establish myself as a confident\, enthusiastic and effective teacher who is able to engage\, encourage and develop students' learning.)}}}

{{{div}}}

{{{cvachievement(\faTrophy,Bristol Plus Award, For undertaking a wide range of tasks to further enhance student skills - only 700 out of 23\,000 achieved this award per annum.)}}}

{{{div}}}

{{{cvachievement(\faCertificate, Mary Jones Prize for Mathematics, For outstanding achievements in A Level mathematics @ Ripon Grammar School)}}}

** Languages :noexport:
#+begin_export latex
% \cvsection{Languages}

% \cvskill{English}{5}
% \divider

% \cvskill{Spanish}{4}
% \divider

% \cvskill{German}{3}

% %% Yeah I didn't spend too much time making all the
% %% spacing consistent... sorry. Use \smallskip, \medskip,
% %% \bigskip, \vpsace etc to make ajustments.
% \med-skip
#+end_export

\newpage
** Referees
#+begin_export latex
% \cvref{name}{email}{mailing address}
\cvref{Prof.\ Arthur Richards}{University of Bristol}{arthur.richards@bristol.ac.uk}
% {Address Line 1\\Address line 2}
\divider
\cvref{Dr.\ Carl Henrik Ek}{University of Cambridge}{che29@cam.ac.uk}
% {Address Line 1\\Address line 2}
#+end_export

* Back Matter :ignore:
#+begin_export latex
\end{paracol}
\end{document}
#+end_export
