* Config/Preamble :noexport:
** LaTeX Config
#+LATEX_CLASS: altacv
#+LATEX_HEADER: \columnratio{0.6} % Set the left/right column width ratio to 6:4.
#+LATEX_HEADER: \usepackage[bottom]{footmisc}
*** Bibliograpny
#+LATEX_HEADER: \addbibresource{pankaj.bib}
# #+LATEX_HEADER: \usepackage[citestyle=numeric-comp, maxcitenames=1, maxbibnames=4, doi=false, isbn=false, eprint=true, backend=bibtex, hyperref=true, url=false, natbib=true]{biblatex}
#+LATEX_HEADER: \usepackage[backend=biber,style=alphabetic,sorting=ynt]{biblatex}
** Exporter Settings
#+AUTHOR: Pankaj Godbole
#+EXPORT_FILE_NAME: ./resume.pdf
#+OPTIONS: toc:nil title:nil H:1
** Macros
#+MACRO: small-skip        \smallskip
#+MACRO: med-skip          \medskip
#+MACRO: big-skip          \bigskip
#+MACRO: div               \divider
#+MACRO: par-div           \par\divider
#+MACRO: new-line          \newline
#+MACRO: new-line-med-skip \newline \medskip
#+MACRO: new-line-big-skip \newline \bigskip
#+MACRO: new-page          \newpage
#+MACRO: cvevent           \cvevent{$1}{$2}{$3}{$4}
#+MACRO: cvtag             \cvtag{$1}
#+MACRO: cvachievement     \cvachievement{$1}{$2}{$3}{$4}
* CV Header :ignore:
** Photo & Tagline :ignore:
#+begin_export latex
\name{Pankaj Godbole}
\photoR{2.5cm}{portrait.jpeg}
\tagline{Clojure Developer}
#+end_export
** Personal Info :ignore:
#+begin_export latex
\medskip
\personalinfo{
  \homepage{pankajgodbole.github.io}
  \email{pankajsg@gmail.com}
  \phone{+91 96373 66884}
  \location{Pune, India}
  \github{pankajgodbole}
  \linkedin{pankajgodbole}}
\makecvheader
#+end_export
* CV Column 1 :ignore:
#+begin_export latex
\begin{paracol}{2}
#+end_export
** Summary
{{{small-skip}}}
#+begin_export latex
 \begin{quote}
Skilled engineer with many years of experience in developing mobile, cloud, desktop and embedded software for Android, iOS, JVM, and Web-browser, Linux, macOS and Windows platforms. Skilled in requirements analysis, software architecture, high-level design, coding, testing, deployment and maintenance. Domain experience includes AI, blockchain, and fintech. Available now.
 \end{quote}
#+end_export
{{{big-skip}}}
** Experience
*** Clojure Developer :ignore:
{{{cvevent(Clojure Developer, Higher Order, 2014 -- Ongoing, Pune\, India)}}}
Building software of high quality at competitive rates for both established companies and early-stage startups.
{{{small-skip}}}
- Build cloud, mobile and desktop apps using Web and native tools
- Write back-end server-side APIs and services
- Design and implement responsive front-end user interfaces
- Involved in the full product life-cycle
- Building software PoCs and MVPs to ensure feasibility of an idea
{{{med-skip}}}
{{{cvtag(Clojure)}}} {{{cvtag(ClojureScript)}}} {{{cvtag(React Native)}}} {{{cvtag(SPA)}}} {{{cvtag(FP)}}} {{{cvtag(SQL)}}} {{{cvtag(REST)}}} {{{cvtag(AWS)}}} {{{cvtag(Docker)}}} {{{cvtag(git)}}} {{{cvtag(UI)}}} {{{cvtag(TDD)}}} {{{cvtag(Startups)}}}
*** Senior Engineer – Software :ignore:
{{{par-div}}}
{{{cvevent(Senior Engineer – Software, Logitech Designs India Pvt Ltd, 2010 -- 2013, Chennai\, India)}}}
Built immersive and responsive Android apps and single page applications for universal remote controls and Android TV products
{{{small-skip}}}
- Built an electronic program guide SPA using REST APIs from Rovi
- Served as Scrum Master
{{{med-skip}}}
{{{cvtag(Android)}}} {{{cvtag(Node.js)}}} {{{cvtag(SPA)}}} {{{cvtag(jQuery)}}} {{{cvtag(Bootstrap)}}} {{{cvtag(Jenkins)}}}
*** Android Consultant :ignore:
{{{new-page}}}
{{{cvevent(Android Consultant, Early-stage startups, 2009 -- 2010, Pune\, India)}}}
- Helped early-stage startups on their mobile journey
- Mentored novice Android developers
{{{med-skip}}}
{{{cvtag(Android)}}} {{{cvtag(SQLite)}}} {{{cvtag(XML)}}} {{{cvtag(Mobile)}}} {{{cvtag(Cloud)}}} {{{cvtag(Web)}}}
# {{{cvtag(Teamwork)}}}
*** Software Test Manager :ignore:
{{{div}}}
{{{cvevent(Software Test Manager, Ecrio Inc., 2008 -- 2009, Cupertino\, USA)}}}
- Managed the testing of SIP-based VoIP applications
- Built and led outsourced teams co-located in US and India
{{{med-skip}}}
{{{cvtag(Symbian)}}} {{{cvtag(Windows Mobile)}}} {{{cvtag(MS Project)}}} {{{cvtag(MS Excel)}}} {{{cvtag(Bugzilla)}}}
*** Software Engineer :ignore:
{{{div}}}
{{{cvevent(Software Engineer, Palm Inc., 2006 -- 2007, Sunnyvale\, USA)}}}
- Handled Wi-Fi–Bluetooth coexistence on Treo smartphones
- Worked closely with WLAN and BT hardware engineers
{{{med-skip}}}
{{{cvtag(PalmOS)}}} {{{cvtag(Windows Mobile)}}} {{{cvtag(Wi-Fi)}}} {{{cvtag(Bluetooth)}}} {{{cvtag(Wireshark)}}}
*** Senior Software Engineer :ignore:
{{{div}}}
{{{cvevent(Senior Software Engineer, Veriwave Inc., 2005 -- 2005, Sunnyvale\, USA)}}}
- Validated the VeriWave Command Language via extensive tests
- Tested the generated 802.11 frames at MAC and network layers
{{{med-skip}}}
{{{cvtag(802.11)}}} {{{cvtag(WLAN)}}} {{{cvtag(Python)}}} {{{cvtag(Tcl)}}} {{{cvtag(Wireshark)}}} {{{cvtag(QA)}}}
*** Systems Engineer :ignore:
{{{par-div}}}
{{{cvevent(Systems Engineer, Qorvus Systems, 2004 -- 2005, Vancouver\, USA)}}}
Hardware and software for wireless mesh networking access points (APs) for downtowns, 24/7 wireless video monitoring, remote sensing in industrial applications, etc.
{{{small-skip}}}
- Created new revenue stream through a service called Qspot
- Designed a way to allow AP access by device's MAC address
- Automated signing, granting and revoking security certificates
{{{med-skip}}}
{{{cvtag(Ethernet)}}} {{{cvtag(PoE)}}} {{{cvtag(bash)}}} {{{cvtag(Linux)}}} {{{cvtag(CGI)}}} {{{cvtag(OpenSSL)}}}
*** Systems Analyst :ignore:
{{{par-div}}}
{{{cvevent(Systems Analyst, American Bureau of Shipping, 2000 -- 2001, Houston\, USA)}}}
Developed of advanced 3-tier client-server Web services, enabling engineers to model and analyze complex marine structures.
{{{small-skip}}}
- Lead a team of three engineers through development lifecycle
- Assigned tasks, coordinated the development
- Mentored new team members
{{{med-skip}}}
{{{cvtag(Java)}}} {{{cvtag(VRML)}}} {{{cvtag(Simulation technology)}}} {{{cvtag(XSLT)}}} {{{cvtag(Servlets)}}} {{{cvtag(LAMP)}}} {{{cvtag(Windows 2000)}}}
*** Software Engineer :ignore:
{{{par-div}}}
{{{cvevent(Software Engineer, Patni Computer Systems, 1997 -- 2000, Pune\, India)}}}
Maintained and enhanced advanced CAD/CAM software from Computer Vision and Parametric Technologies Corp.
{{{small-skip}}}
- Ported C and C++ modules from Solaris to Windows NT
- Performed QA based on ISO-9001 and CMM
- Educated team-members about CMM via a series of seminars
{{{med-skip}}}
{{{cvtag(C)}}} {{{cvtag(Fortran)}}} {{{cvtag(Solaris)}}} {{{cvtag(Windows NT)}}} {{{cvtag(CAD/CAM)}}}
# {{{cvtag(Capibility Maturity Model)}}}
{{{new-line-big-skip}}}
** Projects
*** Developing iOS and Android apps :ignore:
{{{cvevent(Developing iOS and Android apps, Urban Dictionary, Mar 2021 - Apr 2021)}}}
Worked on native mobile apps using React Native apps
{{{cvtag(Clojurescript)}}} {{{cvtag(React Native)}}} {{{cvtag(re-frame)}}} {{{cvtag(shadow-cljs)}}} {{{cvtag(Expo.io)}}} {{{cvtag(Docker)}}}
*** UPI Code Migration :ignore:noexport:
{{{div}}}
{{{cvevent(UPI Code Migration, Juspay, Sep 2019 - Mar 2021, Bengaluru\, India)}}}
- Worked on migrating the company’s digital-payments services from PureScript (JavaScript) to Haskell
{{{med-skip}}}
{{{cvtag(Haskell)}}} {{{cvtag(Servant)}}} {{{cvtag(Streamly)}}} {{{cvtag(stack)}}} {{{cvtag(MySQL)}}} {{{cvtag(Intellij IDEA)}}} {{{cvtag(Docker)}}} {{{cvtag(BitBucket)}}}
*** Web scraping and Data Extraction :ignore:
{{{par-div}}}
{{{cvevent(Web scraping and Data Extraction, Accrue Inc., Sep 2019 - Nov 2019, New York\, USA)}}}
- Wrote code to scrape complex web-pages of financial news data, extract all information related to events and persist it to a Postgresql database.
- Speed and accuracy were of paramount importance.
{{{cvtag(Clojure)}}} {{{cvtag(Leiningen)}}} {{{cvtag(EDN)}}} {{{cvtag(Postgresql)}}}
*** IOCoin HTML5 Wallet :ignore:
{{{par-div}}}
{{{cvevent(IOCoin HTML5 Wallet, IO Digital, Jul 2017 - Nov 2017, Miami\, USA)}}}
- Worked on the UI for a Lite Client HD wallet system
{{{cvtag(Node.js)}}} {{{cvtag(Electron)}}} {{{cvtag(C++)}}} {{{cvtag(Mithril)}}} {{{cvtag(Boost)}}}  {{{cvtag(blockchain)}}} {{{cvtag(cryptocurrency)}}} {{{cvtag(HD Wallet)}}}
# {{{new-page}}}
{{{new-line-big-skip}}}
{{{new-page}}}
** Android apps
*** Visitor Management System Android Tablet app :ignore:
{{{cvevent(Visitor Management System Android Tablet app, Cogent Innovations Pvt Ltd, Oct 2015 - Jul 2017, Chennai\, India)}}}
An advanced Android app for a Visitor Management System designed specifically for Android tablets. The app eliminates the need for pen and paper for gathering visitor information. It generates and prints the visitor badge, and also informs the office employee of the visitor waiting for them.
# - Designed and developed this app from the ground up as a "turn key" solution
- \faLink [[https:///www.usetouchpoint.com/visitor-management.html][Cogent TouchPoint]]
{{{cvtag(Android Material Design)}}} {{{cvtag(AppCompat)}}} {{{cvtag(Volley)}}} {{{cvtag(Gson)}}}
*** MealTango :ignore:
{{{par-div}}}
{{{cvevent(MealTango, Albatross Innovations, Jul 2015 - Oct 2015, Pune\, India)}}}
MealTango is an app for a food ordering service. The app enables people interested in enjoying home-cooked meals to order fresh meals cooked by home chefs.
# - Designed, developed and deployed this app up as a "turn key" app
- \faLink [[https://play.google.com/store/apps/details?id=com.mealtango.android][MealTango on Google Play]]
{{{cvtag(Android Material Design)}}} {{{cvtag(AppCompat)}}} {{{cvtag(accelerometer)}}}
*** ShakeICE :ignore:
{{{par-div}}}
{{{cvevent(ShakeICE, Higher Order, May 2015 - Jun 2015, Pune\, India)}}}
In case of an emergency this app enables the user to automatically alert preselected contacts via call and SMS. The app provides the user's current GPS coordinates and street location in the alert.
# - Designed and developed this app from the ground up as a service to the public
- \faLink [[https://www.facebook.com/shakeiceandroid][ShakeICE on Google Play]]
{{{cvtag(Android Material Design)}}} {{{cvtag(AppCompat)}}} {{{cvtag(accelerometer)}}}
*** Dogtainers Checklist App :ignore:
{{{par-div}}}
{{{cvevent(Dogtainers Checklist App, Dogtainers, Feb 2015 - May 2015, Melbourne\, Australia)}}}
This app presents an extensive checklist for pet owners who wish to transport their pets. The user can select the requirements relevant to their pet's move set a date by which to complete each requirement and set up reminders using the Calendar.
# - Designed and developed this app including the UI, database, etc.
- \faLink [[https://www.dogtainers.com.au/][Dogtainers, Australia]]
{{{cvtag(SQLite)}}} {{{cvtag(AppCompat)}}} {{{cvtag(Preferences)}}}
*** Crash Alarm :ignore:
{{{par-div}}}
{{{cvevent(Crash Alarm, G-Force, Oct 2014 - Dec 2014, Brisbane\, Australia)}}}
This Android app is targeted at race-car drivers triggers an SMS alert if the driver crashed their car while racing.
# - Designed and developed this app including the UI, background service, etc.
{{{cvtag(SQLite)}}} {{{cvtag(AppCompat)}}} {{{cvtag(accelerometer)}}}
{{{new-page}}}
** Academic Projects
*** Optimizing the Advanced Encryption Standard (AES) - MS Dissertation project :ignore:
{{{cvevent(Optimizing the Advanced Encryption Standard, Oregon State University, Apr 2003 - Jan 2004)}}}
- MS Dissertation project
- Implemented an optimized version of the AES, achieving 68% speed-up over the then-available implementation
- Employed fast algorithm, efficient data structures, optimal coding techniques and SSE (Streaming SIMD Extensions) instructions resulting in maximum speed of execution
{{{cvtag(C)}}} {{{cvtag(GNU debugger)}}} {{{cvtag(AES)}}} {{{cvtag(Intel Architecture)}}} {{{cvtag(SSE)}}} {{{cvtag(SIMD)}}}
*** Secure Hashing Algorithm (SHA)- Network Security course project :ignore:
{{{par-div}}}
{{{cvevent(Secure Hashing Algorithm (SHA), Oregon State University, Sep 2019 - Mar 2021, Corvallis OR\, USA)}}}
- Network Security course project
- Implemented SHA-1 and researched the role of HMAC-SHA-256-128 algorithm in IPSec standard
{{{med-skip}}}
{{{cvtag(C)}}} {{{cvtag(SHA-1)}}} {{{cvtag(Red Hat Linux)}}} {{{cvtag(make)}}} {{{cvtag(GCC)}}} {{{cvtag(GDB)}}} {{{cvtag(Emacs)}}}
*** Speaker (Person) Verification using Power Density Spectrum - BE Degree project :ignore:
{{{par-div}}}
{{{cvevent(Speaker (Voice) Verification using Power Density Spectrum, Shivaji University, Jan 1997 - May 1997, Kolhpur MH\, India)}}}
- BE Degree project
{{{med-skip}}}
{{{cvtag(C)}}} {{{cvtag(Digital Signal Processing)}}} {{{cvtag(Fast Fourier Transform)}}}
** A day of my life :noexport:
# #+begin_export latex
# % \medskip
# % \cvsection{A Day of My Life}
# % % Adapted from @Jake's answer from http://tex.stackexchange.com/a/82729/226
# % % \wheelchart{outer radius}{inner radius}{
# % % comma-separated list of value/text width/color/detail}
# % \wheelchart{1.5cm}{0.5cm}{%
# %   6/8em/accent!30/{Sleep,\\beautiful sleep},
# %   3/8em/accent!40/Hopeful novelist by night,
# %   8/8em/accent!60/Daytime job,
# %   2/10em/accent/Sports and relaxation,
# %   5/6em/accent!20/Spending time with family
# % }
# % % use ONLY \newpage if you want to force a page break for
# % % ONLY the current column
# % \newpage
# #+end_export

# ** Newpage :ignore:noexport:
# #+BEGIN_EXPORT latex
# \newpage
# #+END_EXPORT

* CV Column 2 :ignore:
# Switch to the right column - will automatically move to the next page.
#+begin_export latex
\switchcolumn
#+end_export
** Skills
*** Languages :ignore:
{{{cvtag(Clojure)}}}
{{{cvtag(Java)}}}
{{{cvtag(C++)}}}
*** Front-end :ignore:
{{{new-line-big-skip}}}
{{{cvtag(ClojureScript)}}}
{{{cvtag(React Native)}}}
*** Back-end :ignore:
{{{new-line-big-skip}}}
{{{cvtag(SQL)}}}
{{{cvtag(REST)}}}
*** Dev-ops :ignore:
{{{new-line-big-skip}}}
{{{cvtag(git)}}}
{{{cvtag(GitHub)}}}
{{{cvtag(AWS)}}}
{{{cvtag(Docker)}}}
*** Design :ignore:
{{{new-line-big-skip}}}
{{{cvtag(Single page applications)}}}
{{{cvtag(Material Design)}}}
{{{cvtag(UI)}}}
*** Software Engineering :ignore:
{{{new-line-big-skip}}}
{{{cvtag(TDD)}}}
{{{cvtag(Functional programming)}}}
{{{cvtag(OOP)}}}
*** Project Management :ignore:
{{{new-line-big-skip}}}
{{{cvtag(Project management)}}}
# {{{cvtag(Fortune 500)}}}
{{{cvtag(Startups)}}}
{{{new-line-big-skip}}}
** Online Presence
#+begin_export latex
\homepage{pankajgodbole.github.io}
\newline \medskip
\github{pankajgodbole}
\newline \medskip
\linkedin{pankajgodbole}}
#+end_export
{{{new-page}}}
** Education
{{{cvevent(MS\ in Computer Engineering, Oregon State University, 2004)}}}
{{{div}}}
{{{cvevent(BE in Electronics and Communication Engineering, Shivaji University, 1997)}}}
** Languages
#+begin_export latex
\cvskill{English}{5}
\divider
\cvskill{Marathi}{4}
\divider
\cvskill{Hindi}{3}
\divider
\cvskill{Urdu}{3}
\divider
\cvskill{Tamil}{2}
#+end_export
{{{new-line-big-skip}}}
** Volunteering
*** Ananda Sangha :ignore:
{{{cvevent(Ananda Sangha)}}}
# ** Referees
# #+begin_export latex
# % \cvref{name}{email}{mailing address}
# \cvref{Prof.\ Arthur Richards}{University of Bristol}{arthur.richards@bristol.ac.uk}
# % {Address Line 1\\Address line 2}
# \divider
# \cvref{Dr.\ Carl Henrik Ek}{University of Cambridge}{che29@cam.ac.uk}
# % {Address Line 1\\Address line 2}
# #+end_export

* Back Matter :ignore:
#+begin_export latex
\end{paracol}
\end{document}
#+end_export
